### ISSUE TITLE
kiosk startup should migrate before using contexts

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#589]
after unpackkiosk installed a new project in an empty database (and if migration did not run), kiosk does not start. Instead we get an error:

> Instantiated a KioskControllerPlugin for fileimportplugin
> trying to import filerepositoryplugin
> importing plugin filerepositoryplugin
> Instantiated a KioskControllerPlugin for filerepositoryplugin
> trying to import login_plugin
> importing plugin login_plugin
> Instantiating login_plugin as FlaskAppPlugin
> playground module loaded
> playground loaded
> trying to import playgroundplugin
> importing plugin playgroundplugin
> Instantiated a KioskControllerPlugin for playgroundplugin
> workstationmanagercontroller module loaded
> trying to import workstationmanagerplugin
> importing plugin workstationmanagerplugin
> Instantiated a KioskControllerPlugin for workstationmanagerplugin
> Traceback (most recent call last):
>   File "e:\python37\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "e:\python37\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "E:\Python37\Scripts\flask.exe\__main__.py", line 7, in <module>
>   File "e:\python37\lib\site-packages\flask\cli.py", line 967, in main
>     cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
>   File "e:\python37\lib\site-packages\flask\cli.py", line 586, in main
>     return super(FlaskGroup, self).main(*args, **kwargs)
>   File "e:\python37\lib\site-packages\click\core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "e:\python37\lib\site-packages\click\core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "e:\python37\lib\site-packages\click\core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "e:\python37\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "e:\python37\lib\site-packages\click\decorators.py", line 73, in new_func
>     return ctx.invoke(f, obj, *args, **kwargs)
>   File "e:\python37\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "e:\python37\lib\site-packages\flask\cli.py", line 848, in run_command
>     app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
>   File "e:\python37\lib\site-packages\flask\cli.py", line 305, in __init__
>     self._load_unlocked()
>   File "e:\python37\lib\site-packages\flask\cli.py", line 330, in _load_unlocked
>     self._app = rv = self.loader()
>   File "e:\python37\lib\site-packages\flask\cli.py", line 388, in load_app
>     app = locate_app(self, import_name, name)
>   File "e:\python37\lib\site-packages\flask\cli.py", line 240, in locate_app
>     __import__(module_name)
>   File "E:\khpp\kiosk\__init__.py", line 18, in <module>
>     app = create_app(config_id="")
>   File "E:\khpp\kiosk\__init__.py", line 14, in create_app
>     kiosk_app = KioskAppFactory.create_app(r"{0}\config\kiosk_config.yml".format(root_path), root_path=root_path)
>   File "e:\khpp\kiosk\core\kioskappfactory.py", line 271, in create_app
>     return cls._create_std_app(config_name, root_path=root_path, static_folder=static_folder)
>   File "e:\khpp\kiosk\core\kioskappfactory.py", line 139, in _create_std_app
>     cls.load_master_view()
>   File "e:\khpp\kiosk\core\kioskappfactory.py", line 345, in load_master_view
>     raise e
>   File "e:\khpp\kiosk\core\kioskappfactory.py", line 342, in load_master_view
>     kioskglobals.identifier_cache = MemoryIdentifierCache(kioskglobals.master_view.dsd)
>   File "e:\khpp\kiosk\sync\sync\core\contextmanagement\MemoryIdentifierCache.py", line 19, in __init__
>     self.rebuild_cache()
>   File "e:\khpp\kiosk\sync\sync\core\contextmanagement\MemoryIdentifierCache.py", line 27, in rebuild_cache
>     cur.execute(select_sql)
>   File "e:\python37\lib\site-packages\psycopg2\extras.py", line 143, in execute
>     return super(DictCursor, self).execute(query, vars)
> psycopg2.errors.UndefinedTable: relation "collected_material" does not exist
> LINE 1: ...") identifier, "uid" uid, 0 "idx_identifier" from "collected...
>                                                              ^

**Comment by urapadmin** [comment]
- [ ] address the unfortunate startup order first: Migration should run before access to the database
- [ ] start migration at the end of unpackkiosk unless --no_migration is set.

**Comment by urapadmin** [comment]
starting migration does not work because I cannot import all the modules needed for it. I am not sure what to do about it. Postponed.
