### ISSUE TITLE
urapdatetimelib missing in unpackkiosk

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#916]
unpackkiosk stopped with:

Traceback (most recent call last):
  File ".\unpackkiosk.py", line 340, in <module>
    import urapstdlib
  File "Z:\urap\transfer\unpackkiosk\urapstdlib.py", line 23, in <module>
    from urapdatetimelib import *
ModuleNotFoundError: No module named 'urapdatetimelib'

**Comment by urapadmin** [comment]
### kiosk version 0.8.25
should be fixed
